### PR TITLE
addDataFrame.Rd documentation RE:date/time format

### PR DESCRIPTION
**Pull request by jasonpott**
I struggled to interpret the documentation for the addDataFrame function in relation to date time formats when writing xlsx.

Outside of Rmarkdown I rarely see the options() function used to control the output of functions. So it wasn't immediately clear that this was what I was supposed to use to control date formats within xlsx.

I have made a suggestion as to how this might be more explicitly communicated.

### CODE REVIEW

**Comment by colearendt** [comment]
Thanks so much for the PR! Unfortunately, this will be overwritten almost immediately by ROxygen - would you mind making the changes here?:
https://github.com/colearendt/xlsx/blob/4ed1d0127fdec1581808656b9c636b0fbd0ac4fd/R/addDataFrame.R#L45-L48

(It's also possible that we could revisit how this date format is passed, and make it an argument! If that seems interesting, a follow-up issue may be a good idea 😄 )

**Comment by jasonpott** [comment]
Thanks for the positive reception.

I'm new to making package PRs so still figuring out the structure of packages. I will make the changes there as you suggest. 

I do think that an additional parameter in the createWorkbook or saveWorkbook functions might be a useful addition.  It seems unlikely that users would want a different date format in different sheets, I may be mistaken.

**Comment by jasonpott** [comment]
Can I clarify that you wish for the changes to be made in [4ed1d01]https://github.com/colearendt/xlsx/commit/4ed1d0127fdec1581808656b9c636b0fbd0ac4fd) I don't seem to be able to edit that file directly.

I can edit in the main branch - shall PR from there?

**Comment by colearendt** [comment]
Closed in favor of #195

**Pull request closed without merging**
