### PR TITLE
added forcePivotTableRefresh and forceFormulaRefresh functions

### PR DESCRIPTION
**Pull request by tk3369**
I've added these new functions to patch an Excel file that does not refresh on open.  This is an essential feature to properly generate Excel reports from a template.

### CODE REVIEW

**Comment by colearendt** [comment]
@tk3369 have you contacted @dragua and discussed whether there is intent to maintain this repo or add additional maintainers?

Also, I noticed your unit tests in commented code.  Are you familiar with the [testthat](https://github.com/hadley/testthat) package?  I find it helpful for unit testing within R.

**Comment by tk3369** [comment]
Hi @colearendt, I haven't contacted @dragua and I guess we're all busy with other things :-) 

Sounds like a good idea to use testthat but I'm not familiar. I'm happy to contribute further if you or anyone else could give it a jump-start.

**Comment by tk3369** [comment]
@dragua do you mind adding me (and @colearendt if he doesn't mind) as committers so we can help maintain the package?  Or better yet we can move this to a community organization (new or any other ones that you're aware of)?

**Comment by colearendt** [comment]
Hey @tk3369 - I am definitely busy with other things, but have been added as a committer (I reached out to Adrian via email).  Since this package has been "stable" for so long and is still quite popular, I started formalizing the test cases in testthat at [colearendt/develop](https://github.com/colearendt/xlsx/tree/develop), but am definitely busy with other things.

From Adrian when I corresponded with him:

> I think a priority is to get the latest POI jars and publish xlsxjars to cran making sure nothing breaks with xlsx.  After that, go ahead and modify things.

Testing in general is quite difficult since it, in some sense, requires re-reading the produced `xlsx` file and ensuring that no functionality has broken.  Ensuring we have good test coverage is important, though, when updating JARs so that we protect against breakages.

**Pull request merged**
